---
title: "Christmas crash data"
output: html_notebook
---

I asked NZTA for data on the number of crashes each hour since 2000. Crashes are
classified as Fatal, Serious injury, minor injury, and no injury.

Initially I am interested in understanding what the variations in the various ratios
of crash types over time - and during holiday periods.

```{r, include=F}
library(tidyverse)
library(ggthemes)
library(RPostgreSQL)
library(zoo)
library(lubridate)
library(here)
library(knitr)
db <- dbConnect(PostgreSQL(), dbname='crashes-18')
```

```{r fig.height=20, message=FALSE, warning=FALSE}

prev_xmas <- function(day) { ymd(paste(year(day) - 1, "12-24", sep='-'))}
xmas <- function(day) { ymd(paste(year(day), "12-24", sep='-')) }
jan_season <- function(day, hour, end) {
  case_when(
    yday(day) < end ~ prev_xmas(day),
    yday(day) == end & hour < 6 ~ prev_xmas(day),
    TRUE ~ xmas(day)
  )
}

crashes <- tbl(db, "crashes") %>%
  collect() %>%
  mutate(xmasEve = case_when(
      month(day) != 1 ~ xmas(day),
      month(day) == 1 ~ case_when(
        wday(prev_xmas(day)) %in% c(1,2,7) ~ jan_season(day, hour, 3),
        wday(prev_xmas(day)) == 2 ~ jan_season(day, hour, 4),
        TRUE ~ jan_season(day, hour, 5)
      )
    ),
    xmas = case_when(
      month(day) == 1 & year(day) != year(xmasEve) ~ TRUE,
      month(day) == 12 & mday(day) > 24 ~ TRUE,
      month(day) == 12 & mday(day) == 24 & hour >= 16 ~ TRUE,
      TRUE ~ FALSE
    ),
    xmasYear = case_when(
      month(day) <= 6 ~ year(day) - 1,
      TRUE ~ year(day)
    ),
    period = case_when(
      hour < 6 ~ 0,
      hour >= 6 & hour < 12 ~ 1,
      hour >= 12 & hour < 18 ~ 2,
      hour >= 16 ~ 3,
      TRUE ~ -1
    ),
    md = paste(month(day), mday(day), sep='-'),
    fakeTime = case_when(
      period == -1 ~ ymd_h(paste(paste('1900', month(day), mday(day), sep='-'), 1)),
      month(day) == 12 ~ ymd_h(paste(paste('2019', month(day), mday(day), sep='-'), period * 6 + 3)),
      TRUE ~ ymd_h(paste(paste('2020', month(day), mday(day), sep='-'), period * 6 + 3))
    )
  )

christmas <- crashes %>%
  group_by(xmasEve) %>%
  summarise(fatal = sum(count[severity == 'Fatal' & !xmas])/sum(count[!xmas]),
            xmas_fatal = sum(count[severity == 'Fatal' & xmas])/sum(count[xmas]),
            fatal_severe = sum(count[severity %in% c('Fatal','Serious') & !xmas])/sum(count[!xmas]),
            xmas_fatal_severe = sum(count[severity %in% c('Fatal','Serious') & xmas])/sum(count[xmas]),
            ratio = xmas_fatal/fatal,
            ratio_sev = xmas_fatal_severe/fatal_severe
            )


christmas2 <- crashes %>%
  group_by(xmasYear) %>%
  summarise(fatal = sum(count[severity == 'Fatal' & !xmas])/sum(count[!xmas]),
            xmas_fatal = sum(count[severity == 'Fatal' & xmas])/sum(count[xmas]),
            fatal_severe = sum(count[severity %in% c('Fatal','Serious') & !xmas])/sum(count[!xmas]),
            xmas_fatal_severe = sum(count[severity %in% c('Fatal','Serious') & xmas])/sum(count[xmas]),
            ratio = xmas_fatal/fatal,
            ratio_sev = xmas_fatal_severe/fatal_severe
            )


newyears <- crashes %>%
  filter(md == '1-1')
```

```{r, fig.height=3}
nym_yearly <- newyears %>% 
  filter(period == 0) %>%
  group_by(Year = year(day), Severity=severity) %>%
  summarise(Count=sum(count,na.rm=T))

ggplot(nym_yearly, aes(x=Year,y=Count)) +
  geom_col() +
  facet_wrap(. ~ reorder(Severity, Count), scales="free_y") + 
  theme_tufte()

ggsave(here("assets/nym_yearly.svg"), width=4, height=2)

nym_yearly %>%
  spread(Severity, Count, fill=0) %>%
  rename_all(tolower) %>%
  rename(nonInjury=`non-injury`) %>%
  write_csv(here('data/nym_yearly.csv'))

kable(newyears %>% filter(period==0) %>% group_by(severity) %>% summarise(count=sum(count)))
```

```{r}
crashes %>% filter(xmas & day > '2000-02-02') %>%
  group_by(xmasYear,severity) %>%
  summarise(count=sum(count)) %>%
  spread(severity, count, fill=0) %>%
  rename_all(tolower) %>%
  rename(nonInjury=`non-injury`) %>%
  write_csv(here('data/yearly.csv'))
```

Grab some rainfall data

```{r}

rainfall <- read_csv(here('data/average-rainfall.csv'))
xmas_crashes <- crashes %>% filter(xmas)

daily_rainfall <- rainfall %>% 
  inner_join(xmas_crashes, by=("day")) %>%
  add_count(xmasYear) %>%
  group_by(day, rain, xmasYear,n) %>%
  summarise(
            fatal = sum(count[severity %in% c('Fatal')]),
            serious = sum(count[severity == 'Serious']),
            total = sum(count))


```


Look at progress through the year

```{r}
daily <- crashes %>% group_by(day,severity) %>% summarise(count=sum(count)) %>%
  mutate(md=paste(month(day),mday(day),sep='-'))

ydaily <- daily %>%
  group_by(md,severity) %>%
  summarise(average=mean(count), count=sum(count)) %>%
  mutate(fakeDay=ymd(paste('2016',md,sep='-')))

fd <- ydaily %>% group_by(fakeDay, severity) %>% summarise(average=mean(count))

ggplot(fd, aes(fakeDay,average)) + geom_point() + facet_wrap(. ~ severity, scales = "free_y")

```